
apiVersion: mattermost.gpte.opentlc.com/v1alpha1
kind: Mattermost
metadata:
  name: mattermost
spec:
  database:
    drivername: postgres
    name: mattermost
    password: mattermost
    port: 5432
  authentication:
    keycloak:
      realmUrl: keycloak.$ARGOCD_APP_NAMESPACE.svc.cluster.local/auth/realms/openshift
      secret: mattermost