apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhatgov-operators
  namespace: {{ .Release.Namespace }}
spec:
  sourceType: grpc
  image: quay.io/redhatgov/operator-catalog:latest
  displayName: Red Hat NAPS Community Operators
  publisher: RedHatGov
  icon:
    base64data: ""
    mediatype: ""
  updateStrategy:
    registryPoll:
      interval: 30m
