
apiVersion: mattermost.gpte.opentlc.com/v1alpha1
kind: Mattermost
metadata:
  name: mattermost
spec:
  database:
    drivername: postgres
    name: mattermost
    password: mattermost
    port: 5432
  authentication:
    keycloak:
    # need better solution for dynamic namespace name here
      realmUrl: keycloak.dso.svc.cluster.local
      secret: mattermost