apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhatgov-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  displayName: Red Hat NAPS Community Operators
  publisher: RedHatGov
  icon:
    base64data: ""
    mediatype: ""
  updateStrategy:
    registryPoll:
      interval: 30m
