---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-Openshift-keycloak-client
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: cli
    tekton.dev/displayName: "Create the OCP Keycloak Client"
spec:
  description: >-
    This task creates the Keycloak Client used by the RHSSO Operator.
    It uses the namespace defined in admin-creds secret (this was created by the create-admin-secret task).
  params:
  - name: DOMAIN
    description: Your Openshift Domain
    type: string
    default: "crc.testing"
  - name: APPS_SUBDOMAIN
    description: Your Openshift Apps Subdomain 
    type: string
    default: "apps-crc.testing"
  - name: CLIENT_NAME
    description: Keycloak Client Name
    type: string
    default: "openshift"
  - name: CLIENT_ID
    description: Keycloak Client ID
    type: string
    default: "openshift"
  - name: CLIENT_SECRET
    description: Keycloak Client Secret
    type: string
    default: "openshift"
  - name: VERSION
    description: The OpenShift Version to use
    type: string
    default: '4.6'
  steps:
    - name: create-keycloak-client
      env:
        - name: secretNAMESPACE
          valueFrom:
            secretKeyRef:
              key: namespace
              name: admin-creds
      image: quay.io/openshift/origin-cli:$(params.VERSION)
      script: |
        oc project $secretNAMESPACE
        oc apply -f - << EOF
        apiVersion: keycloak.org/v1alpha1
        kind: KeycloakClient
        metadata:
          name: openshift-client
          namespace: $secretNAMESPACE
          labels:
            app: rhsso
        spec:
          realmSelector:
            matchLabels:
              app: rhsso
          client:
            clientId: $(params.CLIENT_ID)
            secret: $(params.CLIENT_SECRET)
            name: $(params.CLIENT_NAME)
            enabled: true
            clientAuthenticatorType: client-secret
            publicClient: false
            redirectUris:
              - "https://console-openshift-console.$(params.APPS_SUBDOMAIN)/*"
              - "https://api.$(params.DOMAIN)/*"
              - "https://oauth-openshift.$(params.APPS_SUBDOMAIN)/*"
            rootUrl: 'https://console-openshift-console.$(params.APPS_SUBDOMAIN)/'
            protocol: openid-connect
            standardFlowEnabled: true
        EOF
        
