---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: oc-create-admin-secret
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: cli
    tekton.dev/displayName: "openshift client"
spec:
  description: >-
    This task consumes the cluster admin username/password credentials and
    creates a secret in the current working namespace.
  params:
    description: The OpenShift Version to use
    type: string
    default: "4.6"
  - name: USERNAME
    description: Openshift Admin username
    type: string
  - name: PASSWORD
    description: Openshift Admin password
    type: string
  resources:
    inputs:
      - name: source
        type: git
        optional: true
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:$(params.VERSION)
      script: |
        oc create secret generic admin-creds --from-literal=username=$(params.USERNAME) --from-literal=password=$(params.PASSWORD)