---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: cli
    tekton.dev/displayName: "openshift client"
spec:
  description: >-
    This tasks uses an existing secret, admin-creds, to copy the router-ca from the openshift-ingress-operator namespace
  workspaces:
  - name: credentials
    emptyDir: {}
    secret:
      secretName: admin-creds
  params:
  - name: SCRIPT
    description: The OpenShift CLI arguments to run
    type: string
    default: "oc $@"
  - name: ARGS
    description: The OpenShift CLI arguments to run
    type: array
    default:
    - "help"
  - name: VERSION
    description: The OpenShift Version to use
    type: string
    default: "4.6"
  - name: secretUSERNAME
  - name: secretPASSWORD
  resources:
    inputs:
      - name: source
        type: git
        optional: true
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:$(params.VERSION)
      script: "$(params.SCRIPT)"
      args:
        - "$(params.ARGS)"
    