---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: patch-gitea-deployment-with-openshift-certs
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: cli
    tekton.dev/displayName: "openshift client"
spec:
  description: >-
    This task will run an oc patch on the gitea deployment to add in the router-ca into /etc/ssl/certs folder of the pod. We do this so that gitea can trust the self signed cert from our keycloak environment.
  params:
  - name: OPENSHIFT_CERT_SECRET
    description: The OpenShift CLI arguments to run
    type: string
    default: "router-ca"
  - name: VERSION
    description: The OpenShift Version to use
    type: string
    default: "4.6"
  resources:
    inputs:
      - name: source
        type: git
        optional: true
  steps:
    - name: patch-deployment-gitea
      image: quay.io/openshift/origin-cli:$(params.VERSION)
      script: |
        oc patch deployments/gitea -p '{"spec":{"template":{"spec":{"containers":[{"name": "gitea","volumeMounts":[{"name":"openshift-cert","mountPath":"/etc/ssl/certs"}]}],"volumes":[{"name":"openshift-cert","secret":{"secretName":"$(params.OPENSHIFT_CERT_SECRET)","items":[{"key":"tls.crt","path":"tls.crt"},{"key":"tls.key","path":"tls.key"}]}}]}}}}'