apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mattermost-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: mattermost-operator
  source: redhatgov-operators
  sourceNamespace: openshift-marketplace